# Generated by Django 5.0.1 on 2025-10-29 14:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models
from django.db.models import Sum, F, DecimalField, ExpressionWrapper


def populate_existing_outflows(apps, schema_editor):
    Outflow = apps.get_model('outflows', 'Outflow')
    OutflowItem = apps.get_model('outflows', 'OutflowItem')

    value_expr = ExpressionWrapper(
        F('quantity') * F('unit_price'),
        output_field=DecimalField(max_digits=20, decimal_places=2),
    )

    for outflow in Outflow.objects.all():
        total_amount = (
            OutflowItem.objects.filter(outflow=outflow).aggregate(total=Sum(value_expr))['total']
            or Decimal('0')
        )
        outflow.final_amount = total_amount
        outflow.payment_discount_amount = Decimal('0')
        outflow.payment_discount_percentage = Decimal('0')
        outflow.save(update_fields=['final_amount', 'payment_discount_amount', 'payment_discount_percentage'])


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0002_refactor_outflow_sales'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='Percentual de desconto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de pagamento',
                'verbose_name_plural': 'Métodos de pagamento',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='outflow',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20),
        ),
        migrations.AddField(
            model_name='outflow',
            name='operation_type',
            field=models.CharField(choices=[('sale', 'Venda'), ('return', 'Devolução'), ('exchange', 'Troca')], default='sale', max_length=20),
        ),
        migrations.AddField(
            model_name='outflow',
            name='payment_discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='outflow',
            name='payment_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='outflow',
            name='related_outflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_operations', to='outflows.outflow'),
        ),
        migrations.CreateModel(
            name='OutflowReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_records', to='outflows.outflowitem')),
                ('outflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_items', to='outflows.outflow')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outflow_return_items', to='products.product')),
            ],
            options={
                'verbose_name': 'Item devolvido',
                'verbose_name_plural': 'Itens devolvidos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='outflow',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outflows', to='outflows.paymentmethod'),
        ),
        migrations.RunPython(populate_existing_outflows, migrations.RunPython.noop),
    ]
