# Generated by Django 5.0.1 on 2025-11-01 19:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0003_paymentmethod_outflow_final_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='discount_percentage',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='fee_payer',
            field=models.CharField(choices=[('merchant', 'Lojista (desconto)'), ('customer', 'Cliente (acréscimo)')], default='merchant', help_text='Lojista = desconto no valor | Cliente = acréscimo no valor', max_length=10, verbose_name='Quem paga a taxa'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='fee_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentual aplicado (pode ser desconto ou acréscimo)', max_digits=5, verbose_name='Percentual de taxa/desconto'),
        ),
    ]
