# Generated by Django 5.0.1 on 2025-11-03 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outflows', '0004_remove_paymentmethod_discount_percentage_and_more'),
        ('pos', '0002_paymentmethod_alter_salepayment_payment_method'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outflow',
            name='payment_method',
        ),
        migrations.AlterModelOptions(
            name='outflow',
            options={'ordering': ['-created_at'], 'verbose_name': 'Saída Não Faturada', 'verbose_name_plural': 'Saídas Não Faturadas'},
        ),
        migrations.AlterModelOptions(
            name='outflowitem',
            options={'ordering': ['id'], 'verbose_name': 'Item de Saída', 'verbose_name_plural': 'Itens de Saída'},
        ),
        migrations.RemoveField(
            model_name='outflow',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='outflow',
            name='final_amount',
        ),
        migrations.RemoveField(
            model_name='outflow',
            name='operation_type',
        ),
        migrations.RemoveField(
            model_name='outflow',
            name='payment_discount_amount',
        ),
        migrations.RemoveField(
            model_name='outflow',
            name='payment_discount_percentage',
        ),
        migrations.RemoveField(
            model_name='outflow',
            name='related_outflow',
        ),
        migrations.AddField(
            model_name='outflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outflows_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='outflow',
            name='outflow_type',
            field=models.CharField(choices=[('expiration', 'Vencimento'), ('gift', 'Presente/Doação'), ('damage', 'Avaria/Quebra'), ('defect', 'Defeito de Fabricação'), ('personal_use', 'Uso Próprio'), ('loss', 'Perda/Extravio'), ('sample', 'Amostra Grátis'), ('other', 'Outros')], default=1, max_length=20, verbose_name='Tipo de Saída'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='outflow',
            name='recipient',
            field=models.CharField(blank=True, help_text='Pessoa ou entidade que recebeu (se aplicável)', max_length=200, null=True, verbose_name='Destinatário'),
        ),
        migrations.AddField(
            model_name='outflowitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Detalhes específicos deste item', null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='outflow',
            name='description',
            field=models.TextField(default=1, help_text='Descreva o motivo da saída', verbose_name='Descrição/Motivo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.AlterField(
            model_name='outflowitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='outflowitem',
            name='outflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outflows.outflow', verbose_name='Saída'),
        ),
        migrations.AlterField(
            model_name='outflowitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outflow_items', to='products.product', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='outflowitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='outflowitem',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Custo Unitário'),
        ),
        migrations.AlterField(
            model_name='outflowitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Preço de venda de referência', max_digits=20, verbose_name='Preço Unitário'),
        ),
        migrations.AlterField(
            model_name='outflowitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Atualização'),
        ),
        migrations.DeleteModel(
            name='OutflowReturnItem',
        ),
        migrations.DeleteModel(
            name='PaymentMethod',
        ),
    ]
