# Generated by Django 5.0.1 on 2025-11-04 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymentmethod',
            table=None,
        ),
    ]
