# Generated by Django 5.0.1 on 2025-11-03 15:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentual aplicado (pode ser desconto ou acréscimo)', max_digits=5, verbose_name='Percentual de taxa/desconto')),
                ('fee_payer', models.CharField(choices=[('merchant', 'Lojista (desconto)'), ('customer', 'Cliente (acréscimo)')], default='merchant', help_text='Lojista = desconto no valor | Cliente = acréscimo no valor', max_length=10, verbose_name='Quem paga a taxa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Método de pagamento',
                'verbose_name_plural': 'Métodos de pagamento',
                'db_table': 'outflows_paymentmethod',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='salepayment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_payments', to='pos.paymentmethod', verbose_name='Método de pagamento'),
        ),
    ]
