# Generated by Django 5.0.1 on 2025-11-04 16:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('pos', '0002_alter_paymentmethod_table'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('finalized', 'Finalizada'), ('partially_returned', 'Parcialmente Devolvida'), ('fully_returned', 'Totalmente Devolvida'), ('cancelled', 'Cancelada')], default='draft', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('completed', 'Concluída')], default='pending', max_length=20, verbose_name='Status')),
                ('reason', models.TextField(help_text='Descrição do motivo da devolução', verbose_name='Motivo da devolução')),
                ('refund_method', models.CharField(choices=[('credit', 'Crédito em conta'), ('cash', 'Dinheiro'), ('card', 'Cartão'), ('pix', 'PIX')], default='credit', help_text='Como o valor será devolvido ao cliente', max_length=20, verbose_name='Método de reembolso')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Valor base dos produtos devolvidos (sem taxas)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Valor total devolvido')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Aprovado em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Concluído em')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Gerente/admin que aprovou', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns_approved', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado por')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='customers.customer', verbose_name='Cliente')),
                ('ledger_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_source', to='pos.ledgerentry', verbose_name='Lançamento de crédito')),
                ('original_sale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='pos.sale', verbose_name='Venda original')),
                ('user', models.ForeignKey(help_text='Usuário que processou a devolução', on_delete=django.db.models.deletion.PROTECT, related_name='returns_processed', to=settings.AUTH_USER_MODEL, verbose_name='Processado por')),
            ],
            options={
                'verbose_name': 'Devolução',
                'verbose_name_plural': 'Devoluções',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade devolvida')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Preço pelo qual foi vendido', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Preço unitário')),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Total do item')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='products.product', verbose_name='Produto')),
                ('return_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.return', verbose_name='Devolução')),
                ('sale_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='pos.saleitem', verbose_name='Item da venda original')),
            ],
            options={
                'verbose_name': 'Item devolvido',
                'verbose_name_plural': 'Itens devolvidos',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['original_sale', 'status'], name='pos_return_origina_eb40f7_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['customer', 'status'], name='pos_return_custome_0c77bb_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['status', 'created_at'], name='pos_return_status_265386_idx'),
        ),
    ]
