# Generated by hand for initial customers app migration
from django.db import migrations, models
import django.utils.timezone
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome completo')),
                ('date_of_birth', models.DateField(verbose_name='Data de nascimento')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('address', models.TextField(blank=True, verbose_name='Endereço')),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='Informe um CPF válido no formato 000.000.000-00 ou apenas números.', regex='^(\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}|\\d{11})$')], verbose_name='CPF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['full_name'],
            },
        ),
    ]
