# Generated by Django 5.0.1 on 2025-10-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customer_cpf_alter_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(blank=True, help_text='CPF (apenas números)', max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Telefone com DDD (apenas números)', max_length=15, unique=True, verbose_name='Telefone'),
        ),
    ]
