# Generated by Django 5.0.1 on 2025-11-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_cpf_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_generic',
            field=models.BooleanField(default=False, help_text='Indica se é o cliente genérico usado no PDV', verbose_name='Cliente genérico'),
        ),
    ]
