# Generated by Django 5.0.1 on 2025-11-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Faça upload de uma imagem do produto (JPG, PNG)', null=True, upload_to='products/', verbose_name='Imagem do Produto'),
        ),
    ]
